---
- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443

  tasks:    
  - name: CREATE BASIC POLICY PACKAGE
    fmgr_fwpol_package:
      adom: "FWC"
      mode: "add"
      name: "ans-test"
      object_type: "pkg"
