---
- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     adom_name: "EPNFWS01"
     vdom_name: my-vdom

  tasks:
  - name: 'task to get adom sync status'
    fmgr_generic:
         method: "get"
         params:
          - url: "/dvmdb/device/{{adom_name}}"
            #verbose: 1
    register: jsoncontent
    
  - local_action: copy content={{ jsoncontent }} dest=/var/tmp/junk

   
  - name: taking out sync status of device from file.
    shell: cat /var/tmp/junk |awk -F, '{print $11}' |grep conf_status |awk '{print $2}'|cut -f2 -d'"'
    register: sync_status

    #- name: Print out sysnc status
    #debug:
    #       msg: "{{ sync_status }}"
            
  - name: Sending an e-mail of device status
    community.general.mail:
      host: smtp.gmail.com
      port: 587
      username: 7877921@gmail.com
      password: mysecret
      to: RL <21090778@infradynamic.com>
      subject: Device sysnc status update
      body: adom {{ adom_name }} is out of sync.
    delegate_to: localhost
    when: sync_status == "outofsync"
