- name: gathering fortimanager facts
  hosts: fortimanagers
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
   - name: retrieve all the meta data
     fmgr_fact:
       facts:
           selector: 'system_meta'
           params:
               adom: 'FWC'
               meta: ''
