- hosts: kent
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     source_template: "{{ lookup('file', 'templates/switch-config.j2') }}"

  tasks:

  - debug: var=source_template   
    tags:
      - test    
  - name: Script table.
    fmgr_dvmdb_script:
        bypass_validation: False
        workspace_locking_adom: "FWC"
        workspace_locking_timeout: 300
        rc_succeeded: 0
        rc_failed: -2
        adom: "FWC"
        state: present
        dvmdb_script:
           content:
                   
                "{{source_template}}"
           desc: "first script"
           filter_device: 0
           name: "sanjay"
           target: "device_database"
           type: cli          
