---
- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     adom_name: FWC
     vdom_name: my-vdom

  tasks:
  - name: 'get the submit session id'
    fmgr_generic:
         method: "get"
         params:
          - url: "/dvmdb/adom/FWC/workflow"
            #verbose: 1
    register: command_output 

  - name: display out
    debug:
      var: command_output 

  - name: Write variable to file
    local_action: copy content="{{command_output}}" dest=./templates/session_id.j2    
  
  - name: Append Task Sessionid Variable in vars file

    lineinfile:
      dest: ./templates/session_id.j2
      line: sessionid
    check_mode: yes
    register: useless_way

