---
- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Assign or unassign global policy package to ADOM packages.
     fmgr_securityconsole_assign_package:
        bypass_validation: False
        workspace_locking_adom: "FWC"
        workspace_locking_timeout: 300
        rc_succeeded: 0
        rc_failed: -2
        securityconsole_assign_package:
           flags:
             - cp_all_objs
             - copy_assigned_pkg
           pkg: "my-pkg"
           target:
             -
                 adom: "FWC"
                 excluded: disable
                 pkg: "my-pkg"
