- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: no description
     fmgr_system_interface:
        bypass_validation: False
        workspace_locking_adom: FWC
        workspace_locking_timeout: 300
        rc_succeeded: 0
        rc_failed: 2
        state: present
        system_interface:
           alias: null
           allowaccess:
             - ping
             - https
             - ssh
           description: "testing only"
           ip: "192.168.5.100/24" 
           #- "192.168.5.230"
           #  - "255.255.255.0"  
           #mtu: 8198
           name: "my-intf"
           #serviceaccess:
           # - fgtupdates
           # - fclupdates
           # - webfilter-antispam
           #speed: auto
           # status: down
           #rating-service-ip: null
           #update-service-ip: null



