- name:  Copy and install a policy package to devices
  fmgr_securityconsole_install_package:
      bypass_validation: False
      workspace_locking_adom: "{{adom_name}}"
      workspace_locking_timeout: 300
      rc_succeeded: 0
      rc_failed: -2
      securityconsole_install_package:
         adom: "{{adom_name}}"
         adom_rev_comments: "Test"
         adom_rev_name: "2021-10-04_v1"
         dev_rev_comments: "test_version"
         flags:
           - cp_all_objs
           - generate_rev
         pkg: "{{policy_pkg_name}}"
         scope:
           -
               name: "{{adom_name}}"
               vdom: "{{vdom_name}}"

- name: Copy and install a policy package to devices.
  fmgr_securityconsole_install_package:
        bypass_validation: False
        workspace_locking_adom: "{{adom_name}}"
        workspace_locking_timeout: 300
        rc_succeeded: 0
        rc_failed: -2
        securityconsole_install_package:
           adom: "{{adom_name}}"
           adom_rev_comments: "for test only"
           adom_rev_name: "rev-1.2"
           dev_rev_comments: "no comments"
           flags:
             - cp_all_objs
             - generate_rev
           pkg: "{{policy_pkg_name}}"
           scope:
             -
                 name: "{{adom_name}}"
                 vdom: "{{vdom_name}}"

