- name: add pkg policy to vdom
  fmgr_pm_pkg_adom:
        bypass_validation: False
        workspace_locking_adom: "{{adom_name}}"
        workspace_locking_timeout: 300
        rc_succeeded: 0
        rc_failed: -2
        adom: "{{adom_name}}"
        pm_pkg_adom:
           name: "{{policy_pkg_name}}"
           obj ver: 2142
           oid: 21
           package setting:
              central-nat: enable
              consolidated-firewall-mode: enable
              fwpolicy-implicit-log: enable
              fwpolicy6-implicit-log: enable
              inspection-mode: flow
              ngfw-mode: profile-based
              #ssl-ssh-profile: <value of string>
           scope member:
             -
                 name: "{{adom_name}}"
                 vdom: "{{vdom_name}}"
           type: pkg
        
